#! /bin/sh
# Modified by fubar 1/28/2022

pgrep -x sxhkd > /dev/null || sxhkd &

## Modified monitor to divide workspaces across laptop monitor(eDP-1) and external monitor attached to HDMI-1-0
bspc_mon() {
local re	
re="HDMI"
if [[ "$(bspc query -M --names)" =~ $re ]]; then
    bspc monitor eDP-1 -d I II III IV V
    bspc monitor HDMI-1-0 -d VI VII VIII IX X
 else
	  bspc monitor eDP-1 -d I II III IV V VI VII VIII
fi
}
bspc_mon
#bspc monitor eDP-1 -d I II III IV V 
#bspc monitor HDMI-1-0 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           6
#bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

# Default window assigments/placements of launched applications

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a Thunar desktop='^3'
bspc rule -a pyzo desktop='^4'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Custom window assigments/placements of launched applications


# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
## Commented out default active border and used custom orange color hex avlue
#bspc config active_border_color         "#073642"
bspc config active_border_color         "#f77128"
#
# Autostart
## Set display from arandr saved script
set_display() {
local re
re="HDMI"
if [[ "$(xrandr --listactivemonitors)" =~ $re ]]; then
   sh "$HOME"/.screenlayout/dualhead.sh &
else
   sh "$HOME"/.screenlayout/monitor.sh &
fi
}
set_display 

#sh ~/.screenlayout/monitor.sh &
#Set display(s) from custom script
#~/bin/display.sh &

# Bar
#~/.config/polybar/launch.sh &
"$HOME"/.config/bspwm/themes/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
## Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
# Picom
boot_picom() {
#boot picom if it exists
if  type -P picom &>/dev/null; then
    while pgrep -i picom; do
        pkill picom
        sleep 0.5
    done
 (picom --config "$HOME"/.config/picom.conf || exit 1) &> /dev/null &
fi
}
boot_picom
#picom -b &
# Network Applet
nm-applet --indicator &

# Kill already running firewall-applet
while pgrep -u "$EUID" -a firewall-applet; do
	pkill firewall-applet
	sleep 0.5
done
/usr/bin/firewall-applet 

# Cursor
xsetroot -cursor_name left_ptr &

#xfce4-power-manager set to handle display, suspend, and hibernate settings such as inactivity, lid closure, power-button actions
xfce4-power-manager &

### Custom apps/scripts to autostart in background on login
#
# ProtonVPN autostart
#/usr/bin/protonvpn &

### For Java applications to run properly in non-reparenting wm (bspwm is such). fixes windowscaling and crash issues
wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1
# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh
